### ISSUE TITLE
vite-plugin-checkerを使用したビルドでエラーが発生する。

### ISSUE THREAD

**Issue by Tsubasa0129ti** [Tsubasa0129ti/template#7]
## 発生したエラー

開発用ビルド実施時に以下のようなエラーが発生している。なお、本番用ビルドでは同様の現象が発生していない。  
開発用ビルドでは、型チェックに`vite-plugin-checker`を使用しており、これが原因ではないかと考えている。

```bash
$ yarn run build
error during build:
Error: Cannot find module 'vue-tsc/out/index'
Require stack:
- /Users/inouetsubasa/application_template/template/web/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at file:///Users/inouetsubasa/application_template/template/web/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js:11:31
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async createCheckers (file:///Users/inouetsubasa/application_template/template/web/node_modules/vite-plugin-checker/dist/esm/main.js:30:37)
    at async config (file:///Users/inouetsubasa/application_template/template/web/node_modules/vite-plugin-checker/dist/esm/main.js:63:18)
    at async runConfigHook (file:///Users/inouetsubasa/application_template/template/web/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:68303:25)
    at async resolveConfig (file:///Users/inouetsubasa/application_template/template/web/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:67760:14)
    at async build (file:///Users/inouetsubasa/application_template/template/web/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:66874:20)
```

**Comment by Tsubasa0129ti** [comment]
`vue-tsc`のバージョン2以降が非対応らしい。https://github.com/fi3ework/vite-plugin-checker/issues/306  
そのため、ひとまずはダウングレードする。
